get_data:
    download_id: "1D-0gn9kJObWDnHXy9_NwI1Us8zCfFlwt"
    data: "../data/restnt_data.csv"
    
    model_id: 1-9wC-IJn6s1V_FOkEtAHmyt8yzMRBfuK
    

data_analysis:
    data: "../data/clean_data.csv"    
    
    city_vs_rating: 
        title: "Rating  Distribution of Cities"
        xlabel: "Cities"
        ylabel: "Rating"
        
    type_vs_rating: 
        title: "Rating  Distribution of Restaurant Types"
        xlabel: "Restaurant Types"
        ylabel: "Rating"
        
    online_vs_rating:
        title: "Online Order vs Rating of Restaurants"
        xlabel: "Rating"
        ylabel: "Total Customers"
        
    book_vs_rating:
        title: "Table Booking vs Rating of Restaurants"
        xlabel: "Rating"
        ylabel: "Total Customers"
    
    top_cuisines:
        title: "Distribution of Top Cuisines Across Restaurants"
        xlabel: "Cuisines"
        ylabel: "Total Restaurants"
        
    cuisines_vs_rating:
        title: "Comparison of Rating of Different Cuisines"
        

prepare_data:
    data: "../data/clean_data.csv"
    
split_data:
    data: "../data/prepared_data.csv"
    
model_data:
    train_set: "../data/train_set.csv"
    train_labels: "../data/train_labels.csv"
    test_set: "../data/test_set.csv"
    test_labels: "../data/test_labels.csv"
    n_estimators: 100

    feature_importance:
        xlabel: "Feature Labels"
        ylabel: "Feature Importances"
        title: "Comparison of Different Feature Importances"
    